parameters:
  mobile_detect.mobile_detector.class: ''
  mobile_detect.device_view.class: ''
  mobile_detect.cookie_key: ''
  mobile_detect.switch_param: ''
  mobile_detect.cookie_expire_datetime_modifier: ''

services:
  mobile_detect.mobile_detector.default:
    class: '%mobile_detect.mobile_detector.class%'

  mobile_detect.device_view:
    class: '%mobile_detect.device_view.class%'
    arguments: ['@?request_stack']
    calls:
      - [setCookieKey, ['%mobile_detect.cookie_key%']]
      - [setCookiePath, ['%mobile_detect.cookie_path%']]
      - [setCookieDomain, ['%mobile_detect.cookie_domain%']]
      - [setCookieSecure, ['%mobile_detect.cookie_secure%']]
      - [setCookieHttpOnly, ['%mobile_detect.cookie_httpOnly%']]
      - [setSwitchParam, ['%mobile_detect.switch_param%']]
      - [setCookieExpireDatetimeModifier, ['%mobile_detect.cookie_expire_datetime_modifier%']]
      - [setRedirectConfig, ['%mobile_detect.redirect%']]
