sudo: false

language:
  - php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - hhvm
  - 7.0
  - 7.1
  - 7.2
  - 7.3

dist: trusty

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION='4.0.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.2.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.1
      env: SYMFONY_VERSION='4.4.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.0.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.1.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.2.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.3.*'
    - php: 7.3
      env: SYMFONY_VERSION='4.4.*'

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --dev --no-interaction --prefer-dist
